# Generated by Django 4.0.4 on 2022-04-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_user_managers_remove_user_username_user_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
